### ISSUE TITLE
how to add message details?

### ISSUE THREAD

**Issue by jiyinyiyong** [zcong1993/actions-ding#2]
README 上是静态的消息, 我打算定制具体消息内容的话, 怎么弄?

**Comment by zcong1993** [comment]
参考这个例子, actions 之间传值原理是一样的. 
https://help.github.com/cn/actions/configuring-and-managing-workflows/configuring-a-workflow#creating-a-workflow-file

![image](https://user-images.githubusercontent.com/18305255/76276488-f3198400-62c0-11ea-952e-b25ea1a21a30.png)
