### ISSUE TITLE
v3.0.2 使用同样的配置一直报“缺少参数 json” 错误 

### ISSUE THREAD

**Issue by redstone1994** [zcong1993/actions-ding#5]

**Comment by redstone1994** [comment]
![image](https://user-images.githubusercontent.com/26979634/140905665-c494e951-bdf1-42e5-9960-03e6462595d6.png)
能帮忙看下是为什么吗

**Comment by zcong1993** [comment]
给一个脱敏数据, 格式和你这个一样

**Comment by zcong1993** [comment]
看了下, 问题本质是 actionCard.text 值是个多行文本不是合法 json, 但是 dingding 服务端是支持这种的. 已经在 v3.0.3 修复.
